runtime: python
env: flex

runtime_config:
    operating_system: "ubuntu22"
    runtime_version: "3.9"

entrypoint: streamlit run main.py --server.port $PORT

automatic_scaling:
  max_num_instances: 1

